name: Test
version: 1.0-SNAPSHOT
main: me.masterbea.test.Test
api-version: 1.13
authors: [masterbea]
description: test

commands:
  hi:
    usage: /<command>
    description: Tutorial Command
  wand:
    usage: /<command>
    description: gives player a wand